### PR TITLE
Fixes compatibility with Java 7

### PR DESCRIPTION
**Pull request by chebum**
I fixed several places to make the plugin compatible with JDK 7. I believe it's important since Java 7 is still used in about half of all Java projects (https://plumbr.eu/blog/java/java-version-statistics-2015-edition). We're still working on Java 7 as well.

The most important differences are:
* I replaced **Instant** with **Date**. Since Rollbar expects timestamp in seconds, even Date will suffice.
* Added an implementation for **String.join**
* Replaced **getOrDefault** with **get**. All occurrences of getOrDefault used null as "default" parameter value. This means behavior didn't change if we replace it with a get method call. 
* Fixed JavaDoc in TestThat.java

### CODE REVIEW

**Comment by Crisfole** [comment]
Hey, you're the man! I'll run the tests (still need to setup CircleCI for this repo), and review the changes.

Eventually we'll probably need to support 6 as well :( but I wasn't entirely sure how to get it all working in different language versions. (I'm a C# guy impersonating a Java programmer...)

Unrelated question: how does the library "feel" to you? I'm still not 100% sold on the completely immutable objects. I feel like I could probably just make the mandatory fields immutable and get a similar feel with a lot less work involved in altering the payloads...

**Comment by Crisfole** [comment]
Tests Pass! Thanks for this. Any feedback is welcome on this!

**Comment by Crisfole** [comment]
Released. Waiting on Maven Central to sync now.

**Comment by chebum** [comment]
> Unrelated question: how does the library "feel" to you? I'm still not 100% sold on the completely immutable objects. I feel like I could probably just make the mandatory fields immutable and get a similar feel with a lot less work involved in altering the payloads...

I don't feel that's important since most of the time you won't interact with it. I created a singleton object as recommended and that was enough.

**Pull request merged**
