### PR TITLE
Move all Travis build steps to Github action.

### PR DESCRIPTION
**Pull request by diegov**
## Description of the change

This change adds an additional `ci.yml` GH action, which reproduces as closeley as possible all the steps that were being done in Travis CI, and removes the Travis CI configuration. 

## Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

None

### Development

- [x] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

Note there are no automated tests for the GH action nor the Travis configuration, but it has been extensively tested manually, locally where possible, and via numerous pushes to the repo. 

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

### CODE REVIEW

**Comment by diegov** [comment]
Closing, I'll open a new one fromF a branch Clubhouse recognises.

**Comment by bxsx** [comment]
You can just add ch##### as a comment or to description and CH will catch it and integrate.

**Comment by diegov** [comment]
Good to know! That's much better than having to prefix my full name and ch ID to every PR branch!

**Comment by bxsx** [comment]
I actually prefer to have a prefix in branch names as autocompletion works great with this :)

**Comment by Az111z2** [comment]
> ## Description of the change
> This change adds an additional `ci.yml` GH action, which reproduces as closeley as possible all the steps that were being done in Travis CI, and removes the Travis CI configuration.
> 
> ## Type of change
> * [ ]  Bug fix (non-breaking change that fixes an issue)
> * [x]  New feature (non-breaking change that adds functionality)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> 
> ## Related issues
> None
> 
> ## Checklists
> ### Development
> * [x]  Lint rules pass locally
> * [ ]  The code changed/added as part of this pull request has been covered with tests
> * [ ]  All tests related to the changed code pass in development
> 
> Note there are no automated tests for the GH action nor the Travis configuration, but it has been extensively tested manually, locally where possible, and via numerous pushes to the repo.
> 
> ### Code review
> * [ ]   This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
> * [ ]  "Ready for review" label attached to the PR and reviewers mentioned in a comment
> * [ ]  Changes have been reviewed by at least one other engineer
> * [ ]  Issue from task tracker has a link to this pull request

**Pull request closed without merging**
